/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;


public class App {
    

    public static void main(String[] args) {
        Window window = new Window();
        window.run();
        
        
    }
}
